"""empty message

Revision ID: 6572f42b4ba9
Revises: 
Create Date: 2023-01-05 03:38:33.239442

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6572f42b4ba9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("custom_user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("password", sa.String(length=255), nullable=False)
        )
        batch_op.create_unique_constraint(None, ["password"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("custom_user", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("password")

    # ### end Alembic commands ###
