"""empty message

Revision ID: 835651a39967
Revises: 0d94f1b22c50
Create Date: 2023-01-19 23:58:39.572833

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "835651a39967"
down_revision = "0d94f1b22c50"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=200), server_default="", nullable=False),
        sa.Column("body", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "dt_created", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("dt_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("articles")
    # ### end Alembic commands ###
