"""user

Revision ID: 87a5e3deecb6
Revises: 
Create Date: 2022-12-20 03:01:02.405446

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "87a5e3deecb6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "custom_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("is_staff", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("custom_user")
    # ### end Alembic commands ###
