"""add email field to user model

Revision ID: ff92edf69ad6
Revises: c7560f9af0f1
Create Date: 2023-03-03 22:42:41.087652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ff92edf69ad6"
down_revision = "c7560f9af0f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("email", sa.String(length=255), server_default="", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("email")

    # ### end Alembic commands ###
